Update token feature
thephpleague/oauth2-instagram pull request #19
Opened 2022-01-28 21:58 UTC by oddevan

Continuation of PR #18 adding the phpDocBlocks and tests asked for in that PR.

This PR has been filed in the hopes of getting this feature into a shipping version of the library sooner, as I have multiple projects that could use it.

From @solverat's original:

> This PR:
>
> - allows you to exchange a short-lived access token with a long-lived access-token (which should fix Not working #15)
> - allows you to refresh a long-lived token
> - fixes two annotations return types
> - fixes wrong Exception class (IdentityProviderException => InstagramIdentityProviderException)

[API Reference](https://developers.facebook.com/docs/instagram-basic-display-api/guides/long-lived-access-tokens)

2022-01-31 08:11 UTC, solverat commented
@oddevan Thanks for the finishing!

2022-02-03 08:49 UTC, KevinBerkhof commented
Nice job (both of you!). Hopefully @stevenmaguire can add this into a release soon. ?

2022-02-09 16:53 UTC, shadowhand requested changes
Just two minor class renames, and then I will merge and release this. Thanks!

2022-02-09 16:53 UTC, shadowhand commented on src/Grant/IgExchangeToken.php
> +class IgExchangeToken extends AbstractGrant
Let's rename this `InstagramExchangeToken` for clarity.

2022-02-09 16:53 UTC, shadowhand commented on src/Grant/IgRefreshToken.php
> +class IgRefreshToken extends AbstractGrant
Let's rename this `InstagramRefreshToken` for clarity.

2022-02-09 18:41 UTC, oddevan commented
@shadowhand Got it!

2022-02-09 20:23 UTC, shadowhand approved these changes

2022-02-09 20:23 UTC, merged

2022-02-09 20:31 UTC, shadowhand commented
Released version 3.1.0 moments ago.

2022-02-09 20:32 UTC, shadowhand commented on src/Grant/IgExchangeToken.php
> +class IgExchangeToken extends AbstractGrant
Turns out this naming was consistent with the expectations of `GrantFactory` 😓 Sorry about that! I renamed it back.

2022-02-09 20:44 UTC, solverat commented
Nice! 👍